
name: 'hometask'
version: '1.0.0'

profile: 'hometask'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"


models:
  hometask:
    +tags: ["surf"]
    mart:
      +docs:
        node_color: "orange"
      +materialized: table
      +tags: ["marts"] 
    int:
      +docs:
        node_color: "purple"
      +materialized: view
      +tags: ["intermediate"]
    stg:
      +docs:
        node_color: "blue"
      +materialized: view
      +tags: ["staging"]
    src:
      +docs:
        node_color: "green"
      +tags: ["source"] 

